### ISSUE TITLE
Unable to compile on version 2.0.0-rc.4

### ISSUE THREAD

**Issue by anselmhou** [bbottema/ng2-simple-page-scroll#4]
Hi,

Thanks for the great work.  I'm trying out the library on angular2 rc4 and it seems it is broken on this version.... 

Detail of the error as follow:

```
/node_modules/ng2-simple-page-scroll/src/ng2-simple-page-scroll.directive.ts:35:71
Property 'changes' does not exist on type 'Router'.
```

Thank you in advance.
Anselm

**Comment by wuhkuh** [comment]
Got a fix. Will add as pull request.

**Comment by bbottema** [comment]
Now It's not compiling for me anymore.

> src/ng2-simple-page-scroll.directive.ts(35,71): error TS2339: Property 'subscribe' does not exist on type 'Router'.

That's because you didn't update the package.json. I'll see what I can do.

/edit: nope, with Angular 2.0.0 Release Candidate 4 and Angular Router 3.0.0-beta-2 I'm still getting the same error. Apparently, we're supposed to subscribe on router.events, now.

**Comment by bbottema** [comment]
@anselmhou I released an untested version that uses `router.events.subscribe`. I'm note sure if I need to filter on event, so I released as 1.0.3-beta. Please test this version first.

**Comment by bbottema** [comment]
Apparently, we're supposed to subscribe on router.events, now.

**Comment by wuhkuh** [comment]
@bbottema 

I will dig in my project backups to find the culprit once I have some spare time. In the meantime I have been searching on the internet to check what changed.

The top answer at [this StackOverflow question](http://stackoverflow.com/questions/35912932/angular-2-router-event-listener) confirms the fix I had put in place - are you sure it was wrong?

**Comment by bbottema** [comment]
That exact SO answer is what helped me fix it by using
_router.events.subscribe_. I simply updated the angular dependencies and
tried compiling it.

**Comment by bbottema** [comment]
Will be solved by #9.
